"""Initial migration

Revision ID: 30a4a03e50e9
Revises: 623cf3d4bff1
Create Date: 2024-12-24 22:07:08.945910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a4a03e50e9'
down_revision: Union[str, None] = '623cf3d4bff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predictions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('prediction', sa.INTEGER(), nullable=True)
    )
    # ### end Alembic commands ###
