"""Initial migration

Revision ID: 321347f87da5
Revises: fccc0b8e71a3
Create Date: 2025-02-03 23:03:21.402604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321347f87da5'
down_revision: Union[str, None] = 'fccc0b8e71a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('abstract',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approach', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('model', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('evaluation', sa.Text(), nullable=True))
        batch_op.drop_column('code')
        batch_op.drop_column('contribution')
        batch_op.drop_column('performance')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performance', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('contribution', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('code', sa.TEXT(), nullable=True))
        batch_op.drop_column('evaluation')
        batch_op.drop_column('model')
        batch_op.drop_column('approach')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('abstract',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
