"""Initial migration

Revision ID: 666eb1c6d1ff
Revises: 6b4c4324d309
Create Date: 2025-02-20 22:36:03.838688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '666eb1c6d1ff'
down_revision: Union[str, None] = '6b4c4324d309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('report')

    op.create_table('report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('problem', sa.TEXT(), nullable=True),
    sa.Column('approach', sa.TEXT(), nullable=True),
    sa.Column('model', sa.TEXT(), nullable=True),
    sa.Column('dataset', sa.TEXT(), nullable=True),
    sa.Column('evaluation', sa.TEXT(), nullable=True),
    sa.Column('conclusion', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
