"""Initial migration

Revision ID: e836fa109625
Revises: def2b6dfcc78
Create Date: 2024-12-27 02:05:34.659172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e836fa109625'
down_revision: Union[str, None] = 'def2b6dfcc78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mining', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('clip', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('clip')
        batch_op.drop_column('mining')
        batch_op.drop_column('ad')

    # ### end Alembic commands ###
