"""Initial migration

Revision ID: fccc0b8e71a3
Revises: 231269b3f030
Create Date: 2025-02-03 22:56:08.744116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fccc0b8e71a3'
down_revision: Union[str, None] = '231269b3f030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(), nullable=True))

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###
