name: Azure Static Web Apps CI/CD

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'schedule' || (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'))
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cd slides
          npm i -D playwright-chromium
          npm install
      - name: Run build
        env:
          PYTHONPATH: ${{ github.workspace }}
          ENDPOINT: ${{ secrets.ENDPOINT }} 
          APIKEY: ${{ secrets.APIKEY }} 
          CHAT_MODEL: ${{ secrets.CHAT_MODEL }} 
          API_VERSION: ${{ secrets.API_VERSION }} 
        run: |
          python pipeline/scraping.py
          python pipeline/tagging.py
          python pipeline/extracting.py
          python pipeline/reporting.py
          python pipeline/generating.py 
      - name: Run npm export
        run: |
          cd slides
          for file in md/*.md; do
            echo "Processing $file"
            filename=$(basename -- "$file")
            filename_without_extension="${filename%.*}"
            npm run export "$file"
            if [ -f "./$filename_without_extension-export.pdf" ]; then
              mv "./$filename_without_extension-export.pdf" "../frontend/pdf/$filename_without_extension.pdf"
            else
              echo "File ./$filename_without_extension-export.pdf does not exist, skipping move."
            fi
          done
      - name: Run deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_CLIFF_016AE6203 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./frontend" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "." # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_CLIFF_016AE6203 }}
          action: "close"